LANGUAGES = {
    "en": {
        "app_title": "Coffee YT Downloader",
        "url_group": "Video URL",
        "url_placeholder": "Enter YouTube URL...",
        "options_group": "Options",
        "format_label": "Format:",
        "filename_label": "File name:",
        "folder_label": "Folder:",
        "select_folder": "Choose save folder",
        "download_btn": "DOWNLOAD",
        "status_ready": "Status: Ready",
        "status_downloading": "Status: Downloading...",
        "status_done": "Status: Done!",
        "error_no_url": "Error: Please enter a URL!",
        "error_no_folder": "Error: Please select a folder!",
        "success_download": "Download completed successfully!",
        "language_label": "Language",
        "current_folder": "Current folder",
        "progress_group": "Progress",
        "sponsorblock_label": "Skip sponsor segments (SponsorBlock)",
        "skip_no_music_label": "Skip segments without music",
        "filename_placeholder": "Video name (optional)...",
        "status_label": "Status",
        "status_error": "Error",
        "error_title": "Error",
        "success_title": "Success",
        "error_url_empty": "Please enter a URL!",
        "error_folder_empty": "Please select a folder!",
        "cancel_btn": "Cancel",
        "canceling": "Canceling",
        "cancel_title": "Cancel Download",
        "cancelled_message": "Download has been cancelled.",
        "temp_files_remain_message": "Temporary files remain in the folder:",
        "resuming_download": "Resuming download...",
    },
    "vi": {
        "app_title": "Coffee YT Downloader",
        "url_group": "URL Video",
        "url_placeholder": "Nhập URL YouTube...",
        "options_group": "Tùy chọn",
        "format_label": "Định dạng:",
        "filename_label": "Tên file:",
        "folder_label": "Thư mục:",
        "select_folder": "Chọn thư mục lưu",
        "download_btn": "TẢI XUỐNG",
        "status_ready": "Trạng thái: Sẵn sàng",
        "status_downloading": "Trạng thái: Đang tải...",
        "status_done": "Trạng thái: Hoàn tất!",
        "error_no_url": "Lỗi: Vui lòng nhập URL!",
        "error_no_folder": "Lỗi: Vui lòng chọn thư mục lưu!",
        "success_download": "Tải xuống thành công!",
        "language_label": "Ngôn ngữ",
        "current_folder": "Thư mục hiện tại",
        "progress_group": "Tiến trình",
        "sponsorblock_label": "Bỏ qua quảng cáo tài trợ (SponsorBlock)",
        "skip_no_music_label": "Bỏ qua đoạn không có nhạc",
        "filename_placeholder": "Tên video (tùy chọn)...",
        "status_label": "Trạng thái",
        "status_error": "Lỗi",
        "error_title": "Lỗi",
        "success_title": "Thành công",
        "error_url_empty": "Vui lòng nhập URL!",
        "error_folder_empty": "Vui lòng chọn thư mục lưu!",
        "cancel_btn": "Hủy",
        "canceling": "Đang hủy tải xuống",
        "cancel_title": "Hủy tải xuống",
        "cancelled_message": "Quá trình tải xuống đã bị hủy.",
        "temp_files_remain_message": "Các file tạm vẫn còn trong thư mục:",
        "resuming_download": "Đang tiếp tục tải xuống...",


    },
    "jp": {
        "app_title": "Coffee YT ダウンローダー",
        "url_group": "ビデオのURL",
        "url_placeholder": "YouTubeのURLを入力してください...",
        "options_group": "オプション",
        "format_label": "フォーマット:",
        "filename_label": "ファイル名:",
        "folder_label": "フォルダー:",
        "select_folder": "保存フォルダーを選択",
        "download_btn": "ダウンロード",
        "status_ready": "ステータス: 準備完了",
        "status_downloading": "ステータス: ダウンロード中...",
        "status_done": "ステータス: 完了!",
        "error_no_url": "エラー: URLを入力してください!",
        "error_no_folder": "エラー: 保存フォルダーを選択してください!",
        "success_download": "ダウンロードが完了しました!",
        "language_label": "言語",
        "current_folder": "現在のフォルダ",
        "progress_group": "進行状況",
        "sponsorblock_label": "スポンサーセグメントをスキップ (SponsorBlock)",
        "skip_no_music_label": "音楽のない部分をスキップ",
        "filename_placeholder": "ビデオ名（オプション）...",
        "status_label": "ステータス",
        "status_error": "エラー",
        "error_title": "エラー",
        "success_title": "成功",
        "error_url_empty": "URLを入力してください!",
        "error_folder_empty": "保存フォルダーを選択してください!",
        "cancel_btn": "キャンセル",
        "canceling": "ダウンロードをキャンセルしています",
        "cancel_title": "ダウンロードをキャンセル",
        "cancelled_message": "ダウンロードがキャンセルされました。",
        "temp_files_remain_message": "一時ファイルがフォルダに残っています：",
        "resuming_download": "ダウンロードを再開しています...",
    }
}

_current_lang_dict = LANGUAGES["en"]

def set_language(lang):
    global _current_lang_dict
    if lang in LANGUAGES:
        _current_lang_dict = LANGUAGES[lang]
    else:
        print(f"Invalid language: {lang}. Falling back to English.")
        _current_lang_dict = LANGUAGES["en"]

def get_text(key):
    return _current_lang_dict.get(key, key)